### PR TITLE
fix: externalize bun from step bundle

### LINKED ISSUE #393: Could not resolve "bun"
"dev": "bunx --bun workflow build && bun --hot src/dev.ts",

Creating steps bundle at ./.well-known/workflow/v1/step.js
Discovering workflow directives 352ms
✘ [ERROR] Could not resolve "bun"

    src/lib/redis.ts:2:28:
      2 │ import { RedisClient } from "bun";
        ╵                             ~~~~~

  You can mark the path "bun" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "bun"

    ../../node_modules/drizzle-orm/bun-sql/driver.js:1:20:
      1 │ import { SQL } from "bun";
        ╵                     ~~~~~

  You can mark the path "bun" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle.

 ›   Error: Build failed: Build failed with 2 errors:
 ›   src/lib/redis.ts:2:28: ERROR: Could not resolve "bun"
 ›   ../../node_modules/drizzle-orm/bun-sql/driver.js:1:20: ERROR: Could not resolve "bun"

### PR DESCRIPTION
**Pull request by adriandlam**
step bundles were trying to resolve the `bun` package at build-time, which fails because it's only available at runtime.

closes #393

### CODE REVIEW

File: packages/builders/src/node-module-esbuild-plugin.ts [hunk 1]
```diff
@@ -5,19 +5,24 @@ import type * as esbuild from 'esbuild';
 // Match exact Node.js built-in module names:
 // - "fs", "path", "stream" etc. (exact match)
 // - "node:fs", "node:path" etc. (with node: prefix)
+// - "bun" (exact match)
```
Comment (Jarred-Sumner) [inline packages/builders/src/node-module-esbuild-plugin.ts:8]:
```suggestion
// - "bun" (exact match)
// - "bun:*" 
```

File: packages/builders/src/node-module-esbuild-plugin.ts [hunk 2]
```diff
@@ -5,19 +5,24 @@ import type * as esbuild from 'esbuild';
...
 // But NOT "some-package/stream" or "eventsource-parser/stream"
-const nodeModulesRegex = new RegExp(`^(${builtinModules.join('|')})$`);
+const nodeModulesPattern = `(${builtinModules.join('|')})`;
+const nodeModulesRegex = new RegExp(`^${nodeModulesPattern}$`);
+const regex = new RegExp(`^(${nodeModulesPattern}|bun)$`);
```
Comment (Jarred-Sumner) [inline packages/builders/src/node-module-esbuild-plugin.ts]:
```suggestion
const regex = new RegExp(`^(${nodeModulesPattern}|bun|bun:.*)$`);
```

File: packages/builders/src/node-module-esbuild-plugin.ts (hunk 1 above)
Comment (Jarred-Sumner) [reply packages/builders/src/node-module-esbuild-plugin.ts:8]: Probably not a 100% correct suggestion but TLDR there is `bun:sqlite`, `bun:sql`, `bun:test`

File: packages/builders/src/node-module-esbuild-plugin.ts (hunk 2 above)
Comment (Jarred-Sumner) [reply packages/builders/src/node-module-esbuild-plugin.ts]: This is not a 100% correct suggestion but ideally it would ignore specifiers that start with `bun:`

File: packages/typescript-plugin/src/diagnostics.ts [hunk 3]
```diff
@@ -21,6 +21,10 @@ function isBuiltinModule(moduleName: string): boolean {
   return BUILTIN_MODULES.has(moduleName);
 }
 
+function isBunModule(moduleName: string): boolean {
+  return moduleName === 'bun';
```
Comment (Jarred-Sumner) [inline packages/typescript-plugin/src/diagnostics.ts]:
```suggestion
  return moduleName === 'bun' || moduleName.startsWith('bun:');
```

Comment (adriandlam) [reply packages/typescript-plugin/src/diagnostics.ts]: ok awesome, just updated to support `bun:*`. ty @Jarred-Sumner!

**Review by TooTallNate — APPROVED** [review]
