### PR TITLE
DurableAgent: various compatibility fixes

### LINKED ISSUE #848: DurableAgent: Support LanguageModelV3ToolResultOutput for multimodal tool results (images, files)
## Summary

Currently, `DurableAgent.executeTool` always wraps tool results as a text type by JSON stringifying them, even when the tool returns a properly typed `LanguageModelV3ToolResultOutput` with multimodal content (e.g., images, files).

This prevents tools from returning images or files that the LLM can "see" via vision capabilities.

## Current Behavior

In `durable-agent.js`, the `executeTool` function unconditionally stringifies tool results:

```
const toolResult = await execute(parsedInput, { toolCallId, messages, experimental_context });
return {
    type: 'tool-result',
    toolCallId: toolCall.toolCallId,
    toolName: toolCall.toolName,
    output: {
        type: 'text',
        value: JSON.stringify(toolResult) ?? '',  // <-- Always stringified!
    },
};

```

This means if a tool returns:
```
return {
  type: 'content',
  value: [
    { type: 'text', text: 'Here is the image' },
    { type: 'file-data', data: base64ImageData, mediaType: 'image/jpeg' },
  ],
};

```
`return {  type: 'content',  value: [    { type: 'text', text: 'Here is the image' },    { type: 'file-data', data: base64ImageData, mediaType: 'image/jpeg' },  ],};
`
It gets stringified to a text value, and the LLM never "sees" the image.

Expected Behavior
```
executeTool should detect if the tool result is already a valid LanguageModelV3ToolResultOutput and pass it through without modification.
Proposed Solution

```
```
const toolResult = await execute(parsedInput, { toolCallId, messages, experimental_context });

// Check if tool result is already a LanguageModelV3ToolResultOutput
if (isToolResultOutput(toolResult)) {
  return {
    type: 'tool-result',
    toolCallId: toolCall.toolCallId,
    toolName: toolCall.toolName,
    output: toolResult,  // Pass through as-is
  };
}

// Otherwise, wrap as text (current behavior)
return {
    type: 'tool-result',
    ...
};

function isToolResultOutput(result: unknown): result is LanguageModelV3ToolResultOutput {
  if (typeof result !== 'object' || result === null) return false;
  const r = result as { type?: string };
  return ['text', 'json', 'content', 'error-text', 'error-json', 'execution-denied'].includes(r.type ?? '');
}

```
Use Case
Building AI agents that can:
Generate images via tools (e.g., image generation APIs)
Fetch and display images to the LLM for vision analysis
Return file attachments (PDFs, etc.) in tool results

### LINKED ISSUE #975: Duplicate messages rendered in UI when writing custom data parts to the stream before calling agent.stream
I have a workflow that reads data from various sources, streams them to the UI and then invokes the DurableAgent in a multi-chat workflow. I'm noticing that any messages that use the writable and are streamed before we invoke agent.stream are duplicated in the UI. The stream endpoint is only sending the data one time, but useChat is rendering them twice.
This issue has been happening since we upgraded WDK to 4.0.1-beta.49.

This can be reproduced by running flight-booking-app in my fork of [vercel/workflow-examples](https://github.com/avi1989/workflow-examples/tree/repro-duplicate).

I tried implementing the same changes with @workflow/ai 4.0.1-beta.48 and I did not see the duplicate message [here](https://github.com/avi1989/workflow-examples/tree/repro-duplicates-48)

Screenshot without duplicate message
Image

Screenshot with duplicate message
Image

### LINKED ISSUE #1296: DurableAgent `experimental_telemetry` does not emit AI SDK spans for LLM or tool calls
## Summary

`@workflow/ai` `DurableAgent` accepts `experimental_telemetry`, but durable agent turns do not emit the expected AI SDK telemetry spans (`ai.streamText`, `ai.streamText.doStream`, `ai.toolCall`).

In the same app, plain AI SDK `streamText()` calls emit Langfuse/OpenTelemetry spans correctly. Only the durable workflow path is missing.

## Expected behavior

When `experimental_telemetry: { isEnabled: true, functionId, metadata }` is passed to `DurableAgent`, the durable execution path should emit the same AI SDK telemetry shape developers get from `streamText()` / `generateText()`, including:

- `ai.streamText`
- `ai.streamText.doStream`
- `ai.toolCall`

This should work with standard OpenTelemetry setups such as `@vercel/otel` + `langfuse-vercel`.

## Actual behavior

`DurableAgent` stores and forwards telemetry config, but the internal execution path appears to bypass AI SDK telemetry wrappers:

- `DurableAgent` stores `experimental_telemetry`
- `streamTextIterator` forwards it into `doStreamStep`
- `doStreamStep` then calls raw `model.doStream(callOptions)` without applying telemetry
- durable tool execution also bypasses AI SDK `ai.toolCall` tracing helpers

Result:
- plain `streamText()` spans show up
- durable workflow turns do not create observations/spans in Langfuse

## Reproduction

1. Next.js app with `instrumentation.ts` using `registerOTel({ traceExporter: new LangfuseExporter() })`
2. Verify a normal `streamText()` call emits spans in Langfuse
3. Create a `DurableAgent` with `experimental_telemetry: { isEnabled: true, functionId: 'my-agent' }`
4. Run `agent.stream(...)` inside a workflow with tool calls
5. Observe that planner / plain AI SDK traces appear, but durable main-turn spans do not

## Why this seems to be an implementation bug

In the published package:

- `durable-agent.js` stores telemetry on the agent and forwards it during `stream()`
- `stream-text-iterator.js` passes telemetry into `doStreamStep`
- `do-stream-step.js` performs a raw `model.doStream(...)` and does not use the telemetry setting
- `executeTool()` in `durable-agent.js` does not create AI SDK-style `ai.toolCall` spans

So telemetry is exposed in the API surface but not honored by the durable execution path.

## What we need

Please make `DurableAgent` telemetry behavior match AI SDK core behavior.

Acceptable fixes would be:

1. Route durable LLM execution through the same AI SDK telemetry wrappers used by `streamText()` / `generateText()`, or
2. Add an internal telemetry implementation in `@workflow/ai` that preserves the same span names/structure/attributes, including `ai.toolCall`, or
3. Expose an official helper from AI SDK / Workflow so DurableAgent can reuse the supported telemetry path instead of duplicating logic

## Request for regression coverage

Please add a regression test that verifies `DurableAgent` emits telemetry spans when `experimental_telemetry.isEnabled === true`, including:
- outer generation span
- provider call span
- tool call span
- functionId / metadata propagation

### LINKED ISSUE #1376: DurableAgent hardcodes supportedUrls: {} causing AI_DownloadError for image URLs
### Description

`DurableAgent` hardcodes `supportedUrls: {}` when calling `convertToLanguageModelPrompt`, which tells the AI SDK that the model supports **no** image URLs. This forces the SDK to download every image URL via global `fetch`, which is unavailable in the Workflow runtime, causing an `AI_DownloadError`.

### Steps to Reproduce

1. Create a workflow using `DurableAgent` with an Anthropic or OpenAI model
2. Pass messages containing image URL parts (e.g. `{ type: "image", image: new URL("https://example.com/image.png") }`)
3. Call `agent.stream({ messages, ... })`

### Expected Behavior

Image URLs should be passed through to the model provider (Anthropic/OpenAI), which natively supports fetching image URLs server-side. No client-side download should be attempted.

### Actual Behavior

The AI SDK attempts to download the image using global `fetch`, which crashes with:

```
AI_DownloadError: Failed to download https://example.com/image.png:
Error: Global "fetch" is unavailable in workflow functions.
Use the "fetch" step function from "workflow" to make HTTP requests.
```

### Root Cause

In `packages/ai/dist/agent/durable-agent.js`:

```js
const modelPrompt = await convertToLanguageModelPrompt({
    prompt,
    supportedUrls: {},  // <-- hardcoded empty, ignores model's actual declaration
    download: options.experimental_download,
});
```

Meanwhile, the underlying `@ai-sdk/anthropic` provider correctly declares:

```js
supportedUrls: () => ({
    "image/*": [/^https?:\/\/.*$/],
    "application/pdf": [/^https?:\/\/.*$/]
})
```

Because `DurableAgent` overrides this with `{}`, the SDK's `createDefaultDownloadFunction` attempts to download all image URLs instead of passing them through.

### Suggested Fix

Forward the underlying model's `supportedUrls` instead of hardcoding an empty object:

```js
const modelPrompt = await convertToLanguageModelPrompt({
    prompt,
    supportedUrls: await model.supportedUrls,  // forward model's declaration
    download: options.experimental_download,
});
```

Alternatively, if there are reasons to not forward `supportedUrls`, the default `download` function should use the workflow `fetch` step instead of global `fetch`.

### Workaround

Pass a custom `experimental_download` that returns `null` for all URLs:

```ts
const result = await agent.stream({
    messages,
    experimental_download: async (urls) => urls.map(() => null),
    // ...
});
```

### Environment

- `@workflow/ai`: `4.0.1-beta.54`
- `ai`: `6.0.116`
- `@ai-sdk/anthropic`: `3.0.58`
- Deployed on Vercel with Workflow runtime

### PR DESCRIPTION
**Pull request by VaguelySerious**
Closes #1303 : Support prepareStep on DurableAgent constructor with stream-level override
Closes #1302 : Add InferDurableAgentTools and InferDurableAgentUIMessage type helpers
Closes #1376 : Fix AI_DownloadError for image URLs by defaulting to no-op download
Closes #1296 : Add telemetry span support (ai.streamText.doStream, ai.toolCall) via optional @opentelemetry/api
Closes #848: Allow LanguageModelV3ToolResultOutput results to pass through without json parsin
Closes #975: Documents the necessity of `sendStart: false` when writing custom `UIMessageChunk`s

Co-Authored-By: @nicoalbanese

### CODE REVIEW

File: packages/ai/src/agent/do-stream-step.ts [hunk 1]
```diff
@@ -163,7 +164,18 @@ export async function doStreamStep(
     }),
   };
```
Comment (karthikscale3) [inline packages/ai/src/agent/do-stream-step.ts:166]: TLDR; We should emit spans that are compatible with how `aisdk` emits so there is no disruption for the user when it's visualized on langfuse/datadog. I ran a comparison between this change and how `aisdk` does it. 

1. **`operation.name` separator** — PR uses dot (`.`), AI SDK uses space (` `). Change `".${functionId}"` to `" ${functionId}"`.
   [AI SDK reference](https://github.com/vercel/ai/blob/main/packages/ai/src/telemetry/assemble-operation-name.ts#L12-L13)

2. **Missing `resource.name`** — AI SDK always sets `'resource.name': telemetry?.functionId` alongside `operation.name`. PR omits it entirely.
   [AI SDK reference](https://github.com/vercel/ai/blob/main/packages/ai/src/telemetry/assemble-operation-name.ts#L15)

3. **Missing `span.recordException()`** — AI SDK calls `recordException({ name, message, stack })` before `setStatus` for `Error` instances. PR only calls `setStatus`, so stack traces are lost from spans.
   [AI SDK reference](https://github.com/vercel/ai/blob/main/packages/ai/src/telemetry/record-span.ts#L61-L75)

4. **No context propagation** — AI SDK wraps `fn` execution with `context.with(ctx, () => fn(span))` so nested spans parent correctly. PR never imports or uses `context`.
   [AI SDK reference](https://github.com/vercel/ai/blob/main/packages/ai/src/telemetry/record-span.ts#L27-L32)

5. **`initTelemetry`/`recordSpan` two-phase fragility** — AI SDK's `getTracer` is synchronous and stateless (returns `noopTracer` when disabled). PR requires calling `initTelemetry` before `recordSpan` works; without it, telemetry silently no-ops. Fix: make `recordSpan` self-initializing.
   [AI SDK reference](https://github.com/vercel/ai/blob/main/packages/ai/src/telemetry/get-tracer.ts)

## Good to Have

6. **Add `recordInputs`/`recordOutputs`** to `TelemetrySettings` — AI SDK uses these to gate sensitive data. PR records everything unconditionally.
   [AI SDK reference](https://github.com/vercel/ai/blob/main/packages/ai/src/telemetry/telemetry-settings.ts#L18-L31)

7. **Richer span attributes** — PR only sets `ai.model.provider` + `ai.model.id` on doStream, and only `name` + `id` on toolCall. AI SDK also records `ai.prompt.*`, `ai.usage.*`, `ai.response.*`, `gen_ai.*`, `ai.toolCall.args`, `ai.toolCall.result`.
   [AI SDK step attrs](https://github.com/vercel/ai/blob/main/packages/ai/src/telemetry/open-telemetry-integration.ts#L236-L279), [tool attrs](https://github.com/vercel/ai/blob/main/packages/ai/src/telemetry/open-telemetry-integration.ts#L296-L339)

8. **Root `ai.streamText` span** — AI SDK creates a 3-tier hierarchy (root → doStream → toolCall). PR only has doStream + toolCall, no outer span wrapping the full agent loop.
   [AI SDK reference](https://github.com/vercel/ai/blob/main/packages/ai/src/telemetry/open-telemetry-integration.ts#L209-L210)

Comment (VaguelySerious) [reply packages/ai/src/agent/do-stream-step.ts:166]: This should be addressed now

File: package.json [hunk 2]
```diff
@@ -33,7 +33,7 @@
     "test": "turbo test",
     "clean": "turbo clean",
     "typecheck": "turbo typecheck",
-    "test:e2e": "vitest run packages/core/e2e/e2e.test.ts packages/core/e2e/e2e-agent.test.ts",
```
Comment (VaguelySerious) [inline package.json:36]: These were shipped to main without working, so disabling here

File: .changeset/durable-agent-improvements.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@workflow/ai': patch
+---
+
+Add type helpers (`InferDurableAgentTools`, `InferDurableAgentUIMessage`), support `prepareStep` on `DurableAgent` constructor, fix `supportedUrls` causing `AI_DownloadError` for image URLs, and add telemetry span support for `experimental_telemetry`
```
Comment (VaguelySerious) [inline .changeset/durable-agent-improvements.md]:
```suggestion
Add type helpers (`InferDurableAgentTools`, `InferDurableAgentUIMessage`), support `prepareStep` on `DurableAgent` constructor, fix `supportedUrls` causing `AI_DownloadError` for image URLs, and add telemetry span support for `experimental_telemetry`. Fix `LanguageModelV3ToolResultOutput` breaking response when not json compatible.
```

File: workbench/example/workflows/100_durable_agent_e2e.ts [hunk 4]
```diff
@@ -381,3 +427,128 @@ export async function agentToolApprovalE2e() {
...
+      greet: {
+        description: 'Greet',
+        inputSchema: z.object({ n: z.number() }),
+        execute: prepareStepStep,
+      },
+    },
+    prepareStep: ({ stepNumber }) => {
+      stepNumbers.push(stepNumber);
+      return {};
+    },
```
Comment (pranaygp) [inline workbench/example/workflows/100_durable_agent_e2e.ts:460]: I'm curious if prepareStep is typically used as a step function, or used inline in the workflow context itself?

I did a quick scan on AI sdk docs and looks like your example is exactly what it's typically used for :)

Comment (pranaygp) [reply workbench/example/workflows/100_durable_agent_e2e.ts:460]: no action needed - just curious

File: workbench/example/workflows/100_durable_agent_e2e.ts [hunk 5]
```diff
@@ -381,3 +427,128 @@ export async function agentToolApprovalE2e() {
...
+  }>;
+}> {
+  'use step';
+  return {
+    type: 'content',
+    value: [
+      { type: 'text', text: 'Here is the image' },
+      { type: 'file-data', data: 'iVBORw0KGgo=', mediaType: 'image/png' },
+    ],
+  };
```
Comment (pranaygp) [inline workbench/example/workflows/100_durable_agent_e2e.ts:524]: https://ai-sdk.dev/docs/ai-sdk-core/tools-and-tool-calling#multi-modal-tool-results

nit: should we actually use `toModelOutput`? looks like that's the intended way to use it since tool authors typically wouldn't write a tool to return in the model message format, but would use the converter

just to make the e2e tests more real? claude, you might want to validate that ToolLoopAgent also propagates this `toModelOutput` since that example was taken from generateText
