### PR TITLE
fix(ai): strip openai itemID from tool call metadata  

### LINKED ISSUE #880: Bug: DurableAgent + OpenAI Responses API fails on tool calls due to missing required `reasoning` item
#### Summary

When using **DurableAgent** with **OpenAI models via the Responses API**, any response that includes a **tool call** fails with an `AI_APICallError`.

The failure is possibly caused by `providerOptions` containing only an `itemId`, e.g. `providerOptions.openai.itemId`.

This does **not** happen with:
- OpenAI Chat Completions
- Responses API when `itemId` is omitted and `providerOptions` is just an empty object: `{ providerOptions: { openai: {} } }`
- Responses API when `providerOptions` is removed entirely

---

#### Error

```text
AI_APICallError: Item 'fc_0402bf2d292dd7ed00697a35fb10e0819ab0098545c4d0d7f5'
of type 'function_call' was provided without its required 'reasoning' item:
'rs_0402bf2d292dd7ed00697a35f76f98819abe1cc9f4e72dd689'
```

---

#### Root Cause Analysis

In `packages/ai/src/agent/stream-text-iterator.ts`, when `finishReason === 'tool-calls'`, tool calls are appended like this:

```ts
conversationPrompt.push({
  role: 'assistant',
  content: toolCalls.map((toolCall) => ({
    type: 'tool-call',
    toolCallId: toolCall.toolCallId,
    toolName: toolCall.toolName,
    input: JSON.parse(toolCall.input),
  })),
});
```

Later, in this [commit](https://github.com/vercel/workflow/commit/4b43186eeca64548d351a20b5845865086393960) this logic conditionally adds provider metadata:

```ts
...(toolCall.providerMetadata
  ? { providerOptions: toolCall.providerMetadata }
  : {}),
```

Which results in payloads like:

```ts
providerOptions: {
  openai: {
    itemId: 'fc_00d2d30dba352ead00697a3b795b6081958aeedc7ff5fea9a7',
  },
},
```

For the **OpenAI Responses API**, providing a `function_call` item with an `itemId` appears to require the corresponding `reasoning` item to also be present in the request (based on the error). However, removing `providerOptions` entirely works, which suggests this requirement is being triggered specifically by the presence of `itemId`. Since DurableAgent does not include the reasoning item, OpenAI rejects the request.

---

#### Environment

- `workflow`: `4.0.1-beta.48`
- `@workflow/ai`: `4.0.1-beta.49`
- `ai`: `^5.0.118`
- Model:
  ```ts
  import { openai } from '@workflow/ai/openai';

  openai('gpt-5-mini')
  ```

---

#### Repro

1. Clone the example:  
   https://github.com/vercel/workflow-examples/blob/main/flight-booking-app/workflows/chat/index.ts

2. Update the `DurableAgent` model to:
   ```ts
   import { openai } from '@workflow/ai/openai';

   openai('gpt-5-mini')
   ```

3. Run `pnpm dev` and go to `http://localhost:3000`
4. Send any message that triggers a tool call

5. Results in the error shown above.

---

#### Expected Behavior

DurableAgent should either:

- Avoid attaching `providerOptions.openai.itemId` for Responses API tool calls **unless** the required `reasoning` item is also included, or
- Automatically include the corresponding reasoning item when forwarding tool calls to the OpenAI Responses API.

---

#### Impact

This currently makes **DurableAgent + OpenAI Responses API unusable for workflows involving tool calls**, despite being a supported configuration.

### PR DESCRIPTION
**Pull request by michael-han-dev**
### Description

OpenAI's responses API includes an itemId in tool call metadata. When we pass that back in the next request, OpenAI expects the matching reasoning item to be there too. DurableAgent doesn't keep reasoning items around, so tool calls were failing with errors about missing reasoning items. see #880 

This change strips itemId from OpenAI metadata before we add tool calls to conversation history. We still keep other metadata like Gemini's thoughtSignature. We don't need previousResponseId tracking since DurableAgent already sends the full conversation history.

Fixes #880

### How did you test your changes?

Added 3 unit tests: one for stripping just itemId, one for keeping other OpenAI fields, and one for mixed provider metadata. Also tested manually with the flight-booking-app example using openai('gpt-5-mini') and tool calls work now.

### PR Checklist - Required to merge

- [x] 📦 `pnpm changeset` was run to create a changelog for this PR
  - During beta, we only use "patch" mode for changes. Don't tag minor/major versions.
  - Use `pnpm changeset --empty` if you are changing documentation or workbench apps
- [x] 🔒 DCO sign-off passes (run `git commit --signoff` on your commits)

### CODE REVIEW

File: packages/ai/src/agent/stream-text-iterator.ts [hunk 1]
```diff
@@ -474,3 +479,39 @@ function normalizeFinishReason(raw: unknown): FinishReason | undefined {
...
+    } else if (hasOtherOpenaiFields) {
+      return { openai: restOpenai };
+    } else if (hasOtherProviders) {
+      return restProviders;
+    }
+    return undefined;
+  }
+
+  return meta;
+}
```
Comment (bhuvaneshprasad) [inline packages/ai/src/agent/stream-text-iterator.ts:517]: @michael-han-dev — My initial approach followed this pattern, where I did not provide (itemId + reasoningItem) or previousResponseId. However, I later updated the implementation to include previousResponseId and raised PR #886 to address this.

I wanted to confirm my understanding:
> without (itemId + reasoningItem) or previousResponseId, the code will still function, but I’m unclear on whether the reasoning models would be able to access and leverage the prior reasoning text to improve performance. If the reasoning text is not actually available to the models at inference time, this approach may be less effective than intended.

Could you help clarify whether this assumption is correct, or if I might be overlooking something in how the reasoning context is preserved?

Comment (michael-han-dev) [reply packages/ai/src/agent/stream-text-iterator.ts:517]: hi @bhuvaneshprasad thanks for bringing this up! adding previousresponseID would definitely add a bonus of giving the model access to prior reasoning during tool calls. I didn't add it here since it would create a dependency on openai's server-side state, which breaks the self-contained design of durableagent (among other things). wanted to keep this pr minimal and match the existing behaviour.

Comment (michael-han-dev) [reply packages/ai/src/agent/stream-text-iterator.ts:517]: cc: @pranaygp

File: .changeset/quick-pugs-say.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@workflow/ai": patch
+---
+
+strip OpenAI itemId from providerMetadata to fix Responses API tool call errors
```
Comment (VaguelySerious) [inline .changeset/quick-pugs-say.md:5]:
```suggestion
Strip OpenAI itemId from providerMetadata to fix Responses API tool call errors, fixes #880
```

File: packages/ai/src/agent/stream-text-iterator.ts [hunk 3]
```diff
@@ -474,3 +479,39 @@ function normalizeFinishReason(raw: unknown): FinishReason | undefined {
   }
   return undefined;
 }
+
+/**
+ * Strip OpenAI's itemId from providerMetadata (requires reasoning items we don't preserve).
+ * Preserves all other provider metadata (e.g., Gemini's thoughtSignature).
```
Comment (VaguelySerious) [inline packages/ai/src/agent/stream-text-iterator.ts:485]:
```suggestion
 * Preserves all other provider metadata (e.g., Gemini's thoughtSignature).
 * See https://github.com/vercel/workflow/issues/880
```

**Comment by VaguelySerious** [comment]
I'm considering merging this PR first, and the re-evaluating https://github.com/vercel/workflow/pull/886 if @bhuvaneshprasad still wants to pursue that

**Comment by gr2m** [comment]
I followed up based @bhuvaneshprasad comment. I ran into the discrepancy as part of our work for better AI SDK + Workflow compat

https://github.com/vercel/workflow/pull/1444
