### PR TITLE
fix(world-postgres): route Graphile queue execution over workflow HTTP endpoints

### LINKED ISSUE #1416: world-postgres@4.1.0-beta.44 direct execution is unreliable in Next.js production
After upgrading from @workflow/world-postgres@4.1.0-beta.42 to 4.1.0-beta.44, Next.js production deployments began intermittently failing queued workflow/step execution.

Errors:
Step "... not found"
Queue execution failed (404): <!DOCTYPE html> ...
Unable to resolve base URL for workflow queue.

4.1.0-beta.44 changed Postgres world execution from:

Graphile -> localWorld.queue() -> async local execution

to:

Graphile -> inline execution through QueueExecutor

In #1334 

That improved durable rescheduling (on my end, jobs were pending, respecting concurrency limit instead of being immediately dequeued), but it also made Graphile depend on runtime execution transport/registration in a way that appears to not work / be unstable for Next.js production?

Near-term safe fix:

make world-postgres execution HTTP-only
keep Graphile inline ack/reschedule semantics
avoid the in-process direct execution path

### PR DESCRIPTION
**Pull request by NathanColosimo**
This fixes @workflow/world-postgres queue execution in production-shaped Next.js setups by removing the in-process direct executor path and routing Graphile task execution through the workflow HTTP endpoints instead.

Fixes #1416 

adds a focused failing regression in packages/world-postgres/src/queue.test.ts that reproduces the real Step "..." not found failure mode - on the first commit of this PR you should be able to run ```pnpm exec vitest run packages/world-postgres/src/queue.test.ts``` and that test should fail

On the 2nd commit that test should succeed with the queue.ts changes

The error is from packages/world-local/src/storage/steps-storage.ts 

---

- updates packages/world-postgres/src/queue.ts to execute Graphile jobs via /.well-known/workflow/v1/flow and /.well-known/workflow/v1/step instead of trying to direct execute in the world
- updates packages/world-postgres/README.md and packages/world-postgres/HOW_IT_WORKS.md to describe the HTTP-only execution model

---

## WHY it was failing before:
the direct path assumed:

- the right route module had already been loaded
- it was loaded in the same Node process as Graphile
- that process had the right step/workflow registrations in memory

-> not really always true in Next production build

## WHY HTTP works
- HTTP works better because it goes through the actual Next route endpoint

### CODE REVIEW

File: packages/world-postgres/src/queue.ts [hunk 1]
```diff
@@ -1,13 +1,15 @@
...
+import { getWorkflowPort } from '@workflow/utils/get-port';
 import {
   MessageId,
   type Queue,
   QueuePayloadSchema,
   type QueuePrefix,
   type ValidQueueName,
+  WorkflowInvokePayloadSchema,
 } from '@workflow/world';
-import { createLocalWorld, createQueueExecutor } from '@workflow/world-local';
```
Comment (VaguelySerious) [inline packages/world-postgres/src/queue.ts:10]: Since the executor concept in world-local was created just for world-postgres, could we undo the recent changes in world-local too? i.e. anything from https://github.com/vercel/workflow/pull/1334 that isn't needed anymore

Comment (NathanColosimo) [reply packages/world-postgres/src/queue.ts:10]: for sure, do you want that in this PR or other one?

ill do it in this one for now

**Comment by VaguelySerious** [comment]
@NathanColosimo We might undo this change once we verify nextjs fixes/compat. Separately, we might eventually merge the flow and step routes, which would prevent the concurrency gating fix for the flow route you added in this PR from working, also requiring a revert. I assume this is fine, but let me know if you have thoughts. We'll release this soon to covert the in between time
