### PR TITLE
fix: port detection, postgres nitro apps and nitro app testing

### LINKED ISSUE #400: ECONNREFUSED - Queue operation failed
Hey there,
Is there any explanation why I get this error time to time?

```bash
[embedded world] Queue operation failed: TypeError: fetch failed
    at ignore-listed frames {
  [cause]: AggregateError:
      at ignore-listed frames {
    code: 'ECONNREFUSED'
  }
}
```

### PR DESCRIPTION
**Pull request by adriandlam**
- removes `pid-port` from `getPort` method because internally it uses `netstat` which is not reliable
- adds a delay between dev test and e2e test which was causing a race condition between nitro apps rebuilding from cleanup and invoking the first workflow from the e2e test
- fixes starting postgres world in nitro apps

closes #400

### CODE REVIEW

File: packages/world-local/src/config.ts [hunk 1]
```diff
@@ -28,9 +28,12 @@ export const config = once<Config>(() => {
...
  * 2. config.port (explicit port override from args)
- * 3. Auto-detected port via pid-port (primary approach)
- * 4. PORT env var (fallback)
- * 5. Fallback to 3000
+ * 3. PORT env var (set by dev servers like Nitro, Next.js, Vite)
+ * 4. Default to 3000 (standard dev server port)
+ *
+ * Note: Port detection uses pid-port as a candidate source but validates each candidate
+ * with HTTP requests to ensure only actual HTTP server ports are returned, excluding
+ * internal service ports (HMR, metrics) that pid-port alone would detect.
```
Comment (pranaygp) [inline packages/world-local/src/config.ts]: no longer true right?

File: packages/utils/src/get-port.ts [hunk 2]
```diff
@@ -1,23 +1,36 @@
...
+      case 'linux':
+      case 'darwin': {
+        const result = await execAsync(
+          `lsof -i -P -n | grep -w ${pid} | grep LISTEN | awk '{print $9}' | sed 's/.*://' | head -n 1`
+        );
+        port = parseInt(result.stdout.trim(), 10);
+        break;
+      }
+      case 'win32':
+        throw new Error('Not implemented');
```
Comment (pranaygp) [inline packages/utils/src/get-port.ts]: 🤔 let's fix this

File: packages/world-local/src/config.ts (hunk 1 above)
Comment (adriandlam) [reply packages/world-local/src/config.ts]: yup reverted this comment

File: .github/workflows/tests.yml [hunk 3]
```diff
@@ -188,7 +188,7 @@ jobs:
         run: ./scripts/resolve-symlinks.sh workbench/${{ matrix.app.name }}
 
       - name: Run E2E Tests
-        run: cd workbench/${{ matrix.app.name }} && pnpm dev & echo "starting tests in 10 seconds" && sleep 10 && pnpm vitest run packages/core/e2e/dev.test.ts && pnpm run test:e2e
+        run: cd workbench/${{ matrix.app.name }} && pnpm dev & echo "starting tests in 10 seconds" && sleep 10 && pnpm vitest run packages/core/e2e/dev.test.ts && sleep 5 && pnpm run test:e2e
```
Comment (adriandlam) [inline .github/workflows/tests.yml]: race condition between nitro apps rebuilding after dev test cleanup and e2e tests starting

File: packages/utils/src/get-port.ts [hunk 4]
```diff
@@ -1,23 +1,68 @@
...
+            '-v',
+            `pid=${pid}`,
+            '/LISTENING/ && $NF == pid {split($2,a,\":\"); print a[length(a)]; exit}',
+          ],
+          {
+            input: lsofResult.stdout,
+          }
+        );
+        const result = { stdout: awkResult.stdout };
+        port = parseInt(result.stdout.trim(), 10);
```
[the remark this answers is not in the document]
Comment (adriandlam) [reply packages/utils/src/get-port.ts]: untrue

File: packages/utils/src/get-port.ts [hunk 5]
```diff
@@ -1,23 +1,68 @@
...
+          ['/LISTEN/ {split($9,a,":"); print a[length(a)]; exit}'],
+          {
+            input: lsofResult.stdout,
+          }
+        );
+        port = parseInt(awkResult.stdout.trim(), 10);
+        break;
+      }
+
+      case 'win32': {
```
Comment (adriandlam) [inline packages/utils/src/get-port.ts:35]: had to spin up a windows vm for this <picture data-single-emoji=":sadge:" title=":sadge:">:sadge:</picture>

**Comment by adriandlam** [comment]
> LGTM, only downside is we're now using `execa` which seems quite large as a library just for optimizing a small amount of shell commands. After merging this, might be nice to vibe code a refactor follow-up that removes the execa dependency, given the tests look comprehensive, hopefully that's a one-shot

ah yeah i was originally using `execFileSync` but came across `execa` (which is what `pid-port`) was using. i'll do that in a different PR
