### PR TITLE
Fix default export workflow function transformation in workflow mode

### LINKED ISSUE #367: ReferenceError: $$default is not defined - Workflow execution fails in Local World on Turbo monorepo
Workflows fail during execution in Local World with ReferenceError: $$default is not defined when running in a Turbo monorepo environment. The workflow triggers successfully and queues successfully, but fails immediately (within 10ms) during VM context execution.

This error persists across all tested configurations including the exact setup reported as "working" in Issue #35 (workflow@4.0.1-beta.2 + next@16.0.0).

Environment
Operating System: WSL2 Ubuntu (Linux 6.6.87.2-microsoft-standard-WSL2) Node.js: v22.11.0 Package Manager: pnpm 9.15.9 Monorepo Tool: Turborepo 2.3.3 Monorepo Structure:

Shared packages: @waltoria/shared-db (Prisma), @waltoria/uuid-utils
Multiple Next.js apps in apps/ directory
Workflows in: apps/advisor-activity-nexus/workflows/
Deployment Target: Vercel (but testing locally first)

Tested Configurations (ALL FAILED)
#	Next.js	Workflow DevKit	Bundler	Result
1	16.0.1	4.0.1-beta.11	Turbopack	❌ Workflow must be a function, but got "undefined"
2	16.0.1	4.0.1-beta.11	webpack	❌ $$default is not defined
3	16.0.1	4.0.1-beta.15	Turbopack	❌ Server crash: withWorkflow export not found
4	15.1.3	4.0.1-beta.11	webpack	❌ $$default is not defined
5	16.0.0	4.0.1-beta.2	Turbopack	❌ $$default is not defined
Note on Configuration #5: This is the exact configuration reported as working in Issue #35, but it fails in our monorepo environment.

Full bug report attached here as a .md file 

[GITHUB-ISSUE-DRAFT.md](https://github.com/user-attachments/files/23628779/GITHUB-ISSUE-DRAFT.md)

### PR DESCRIPTION
**Pull request by TooTallNate**
Fixed a bug where default export workflow functions with names (e.g., `export default async function testWorkflow()`) would fail at runtime with `ReferenceError: $$default is not defined`. The SWC plugin now correctly keeps the default export as-is and simply adds the workflowId assignment after it, since the function name is available as a binding in the module scope.

Also adds support for anonymous and arrow function default exports, which previously were not being transformed at all.

Fixes #367.

### CODE REVIEW

File: packages/swc-plugin-workflow/transform/tests/fixture/anonymous-default-workflow/output-workflow.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+// Test anonymous default export workflow
+/**__internal_workflows{"workflows":{"input.js":{"default":{"workflowId":"workflow//input.js//defaultWorkflow"}}}}*/;
+const defaultWorkflow = async function() {
```
Comment (pranaygp) [inline packages/swc-plugin-workflow/transform/tests/fixture/anonymous-default-workflow/output-workflow.js]:
```suggestion
const __default = async function() {
```

File: packages/swc-plugin-workflow/transform/tests/fixture/anonymous-default-workflow/output-workflow.js [hunk 2]
```diff
@@ -0,0 +1,8 @@
...
+    const result = await someStep();
+    return result;
+};
+defaultWorkflow.workflowId = "workflow//input.js//defaultWorkflow";
+export default defaultWorkflow;
```
Comment (pranaygp) [inline packages/swc-plugin-workflow/transform/tests/fixture/anonymous-default-workflow/output-workflow.js]:
```suggestion
defaultWorkflow.workflowId = "workflow//input.js//__default";
export default __default;
```

File: packages/swc-plugin-workflow/transform/tests/fixture/workflow-client-property/output-step.js [hunk 3]
```diff
@@ -1,5 +1,5 @@
 // Test workflow functions in client mode
-/**__internal_workflows{"workflows":{"input.js":{"arrowWorkflow":{"workflowId":"workflow//input.js//arrowWorkflow"},"defaultWorkflow":{"workflowId":"workflow//input.js//defaultWorkflow"},"internalWorkflow":{"workflowId":"workflow//input.js//internalWorkflow"},"myWorkflow":{"workflowId":"workflow//input.js//myWorkflow"}}}}*/;
+/**__internal_workflows{"workflows":{"input.js":{"arrowWorkflow":{"workflowId":"workflow//input.js//arrowWorkflow"},"default":{"workflowId":"workflow//input.js//defaultWorkflow"},"internalWorkflow":{"workflowId":"workflow//input.js//internalWorkflow"},"myWorkflow":{"workflowId":"workflow//input.js//myWorkflow"}}}}*/;
```
Comment (pranaygp) [inline packages/swc-plugin-workflow/transform/tests/fixture/workflow-client-property/output-step.js:2]: this looks like a bug no? the function here is called `defaultWorkflow`

File: packages/swc-plugin-workflow/transform/tests/fixture/workflow-client-property/output-workflow.js
Comment (pranaygp) [inline packages/swc-plugin-workflow/transform/tests/fixture/workflow-client-property/output-workflow.js:13]: interesting case of exporting a named default workflow
